update

diff --git a/.config/ytfzf/interfaces/sixel b/.config/ytfzf/interfaces/sixel
--- a/.config/ytfzf/interfaces/sixel
+++ b/.config/ytfzf/interfaces/sixel
@@ -1,8 +1,11 @@
 #!/bin/sh
 
 interface_sixel () {
-    const_SIXEL_UTIL_DIR="$YTFZF_CUSTOM_INTERFACES_DIR/sixel-menu"
-    ! [ -d "$const_SIXEL_UTIL_DIR" ] && die 3 "the sixel-menu utils folder is required for this interface\n"
+    for path in "${YTFZF_CUSTOM_INTERFACES_DIR}/sixel-menu" "${YTFZF_SYSTEM_ADDON_DIR}/interfaces/sixel-menu"; do
+        const_SIXEL_UTIL_DIR="$YTFZF_CUSTOM_INTERFACES_DIR/sixel-menu"
+        [ -d "$const_SIXEL_UTIL_DIR" ] && break
+        false
+    done || die 3 'The sixel-menu folder is required for this interface\n'
 
     video_json_file=$1
     selected_id_file=$2
